/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/intel-secl/k8s-custom-controller/crdSchema/api/hostattributes/v1beta1"
	scheme "github.com/intel-secl/k8s-custom-controller/crdSchema/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HostAttributesesGetter has a method to return a HostAttributesInterface.
// A group's client should implement this interface.
type HostAttributesesGetter interface {
	HostAttributeses(namespace string) HostAttributesInterface
}

// HostAttributesInterface has methods to work with HostAttributes resources.
type HostAttributesInterface interface {
	Create(*v1beta1.HostAttributes) (*v1beta1.HostAttributes, error)
	Update(*v1beta1.HostAttributes) (*v1beta1.HostAttributes, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.HostAttributes, error)
	List(opts v1.ListOptions) (*v1beta1.HostAttributesList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.HostAttributes, err error)
	HostAttributesExpansion
}

// hostAttributeses implements HostAttributesInterface
type hostAttributeses struct {
	client rest.Interface
	ns     string
}

// newHostAttributeses returns a HostAttributeses
func newHostAttributeses(c *CrdV1beta1Client, namespace string) *hostAttributeses {
	return &hostAttributeses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hostAttributes, and returns the corresponding hostAttributes object, and an error if there is any.
func (c *hostAttributeses) Get(name string, options v1.GetOptions) (result *v1beta1.HostAttributes, err error) {
	result = &v1beta1.HostAttributes{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hostattributeses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HostAttributeses that match those selectors.
func (c *hostAttributeses) List(opts v1.ListOptions) (result *v1beta1.HostAttributesList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.HostAttributesList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hostattributeses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hostAttributeses.
func (c *hostAttributeses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hostattributeses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hostAttributes and creates it.  Returns the server's representation of the hostAttributes, and an error, if there is any.
func (c *hostAttributeses) Create(hostAttributes *v1beta1.HostAttributes) (result *v1beta1.HostAttributes, err error) {
	result = &v1beta1.HostAttributes{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hostattributeses").
		Body(hostAttributes).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hostAttributes and updates it. Returns the server's representation of the hostAttributes, and an error, if there is any.
func (c *hostAttributeses) Update(hostAttributes *v1beta1.HostAttributes) (result *v1beta1.HostAttributes, err error) {
	result = &v1beta1.HostAttributes{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hostattributeses").
		Name(hostAttributes.Name).
		Body(hostAttributes).
		Do().
		Into(result)
	return
}

// Delete takes name of the hostAttributes and deletes it. Returns an error if one occurs.
func (c *hostAttributeses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hostattributeses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hostAttributeses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hostattributeses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hostAttributes.
func (c *hostAttributeses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.HostAttributes, err error) {
	result = &v1beta1.HostAttributes{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hostattributeses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
