/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/intel-secl/k8s-custom-controller/crdSchema/api/hostattributes/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostAttributeses implements HostAttributesInterface
type FakeHostAttributeses struct {
	Fake *FakeCrdV1beta1
	ns   string
}

var hostattributesesResource = schema.GroupVersionResource{Group: "crd.isecl.intel.com", Version: "v1beta1", Resource: "hostattributeses"}

var hostattributesesKind = schema.GroupVersionKind{Group: "crd.isecl.intel.com", Version: "v1beta1", Kind: "HostAttributes"}

// Get takes name of the hostAttributes, and returns the corresponding hostAttributes object, and an error if there is any.
func (c *FakeHostAttributeses) Get(name string, options v1.GetOptions) (result *v1beta1.HostAttributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hostattributesesResource, c.ns, name), &v1beta1.HostAttributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributes), err
}

// List takes label and field selectors, and returns the list of HostAttributeses that match those selectors.
func (c *FakeHostAttributeses) List(opts v1.ListOptions) (result *v1beta1.HostAttributesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hostattributesesResource, hostattributesesKind, c.ns, opts), &v1beta1.HostAttributesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.HostAttributesList{ListMeta: obj.(*v1beta1.HostAttributesList).ListMeta}
	for _, item := range obj.(*v1beta1.HostAttributesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostAttributeses.
func (c *FakeHostAttributeses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hostattributesesResource, c.ns, opts))

}

// Create takes the representation of a hostAttributes and creates it.  Returns the server's representation of the hostAttributes, and an error, if there is any.
func (c *FakeHostAttributeses) Create(hostAttributes *v1beta1.HostAttributes) (result *v1beta1.HostAttributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hostattributesesResource, c.ns, hostAttributes), &v1beta1.HostAttributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributes), err
}

// Update takes the representation of a hostAttributes and updates it. Returns the server's representation of the hostAttributes, and an error, if there is any.
func (c *FakeHostAttributeses) Update(hostAttributes *v1beta1.HostAttributes) (result *v1beta1.HostAttributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hostattributesesResource, c.ns, hostAttributes), &v1beta1.HostAttributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributes), err
}

// Delete takes name of the hostAttributes and deletes it. Returns an error if one occurs.
func (c *FakeHostAttributeses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hostattributesesResource, c.ns, name), &v1beta1.HostAttributes{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostAttributeses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hostattributesesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.HostAttributesList{})
	return err
}

// Patch applies the patch and returns the patched hostAttributes.
func (c *FakeHostAttributeses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.HostAttributes, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hostattributesesResource, c.ns, name, pt, data, subresources...), &v1beta1.HostAttributes{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributes), err
}
